openapi: 3.0.0

info:
  title: Shopify - My Store API
  version: 1.0.0
  description: API specification for Shopify namespace and store integration

servers:
  - url: https://api.shopify.com/v1
    description: Base API URL
  - url: ${ACCOUNT_URL}
    description: Account-specific API URL

paths:
  /products:
    get:
      summary: Get Products
      operationId: getProducts
      tags:
        - products
        - inventory
      parameters:
        - name: limit
          in: query
          schema:
            type: string
          description: Number of products to return per page
          example: "10"
        - name: page
          in: query
          schema:
            type: string
          description: Page number for pagination
          example: "1"
        - name: X-Shopify-Access-Token
          in: header
          schema:
            type: string
          description: Shopify access token for authentication
          required: true
      responses:
        '200':
          description: Successfully retrieved products
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '401':
          description: Unauthorized - Invalid access token
        '422':
          description: Unprocessable Entity - Invalid query parameters
        '429':
          description: Too Many Requests - Rate limit exceeded
        '500':
          description: Internal Server Error

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the product
        title:
          type: string
          description: The name of the product
        description:
          type: string
          description: The description of the product
        vendor:
          type: string
          description: The vendor of the product
        product_type:
          type: string
          description: The type of the product
        created_at:
          type: string
          format: date-time
          description: The date and time when the product was created
        updated_at:
          type: string
          format: date-time
          description: The date and time when the product was last updated
        published_at:
          type: string
          format: date-time
          description: The date and time when the product was published
        variants:
          type: array
          items:
            $ref: '#/components/schemas/ProductVariant'
        images:
          type: array
          items:
            $ref: '#/components/schemas/ProductImage'

    ProductVariant:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the variant
        title:
          type: string
          description: The name of the variant
        price:
          type: string
          description: The price of the variant
        sku:
          type: string
          description: The SKU of the variant
        inventory_quantity:
          type: integer
          description: The quantity of the variant in stock

    ProductImage:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the image
        src:
          type: string
          description: The URL of the image
        position:
          type: integer
          description: The position of the image in the product's image list
        alt:
          type: string
          description: Alternative text for the image

  securitySchemes:
    accountAuth:
      type: apiKey
      in: header
      name: X-Shopify-Access-Token
      description: Shopify access token for API authentication

security:
  - accountAuth: [] 